#!/bin/bash -eu
# Make sure there's at least SOMETHING mapped to ip or Ubuntu gets cranky

hostname=$(hostname)
ip=$(ifconfig eth0 | grep "^ *inet " | sed -e 's/ B.*//' -e 's/.*://')
if ! perl -MSocket -e "gethostbyname('$hostname') || exit 1"; then
	if grep -q "^$ip" /etc/hosts; then
		# just add hostname
		sed "/^$ip:/ s/\$/ $hostname/" /etc/hosts
	else
		echo -e "\n$ip $hostname" >> /etc/hosts
	fi
fi
